### ISSUE TITLE
Removal job punishment

### ISSUE THREAD

**Issue by talarmin29** [KB-RolePlay/tools-issues#55]
### Version

v2.0.16

### Description

When you delete a job punishment, the action is displayed in the logs but it is not executed.

### Expected behaviour

Effective removal.

### Reproduction steps

```bash
1. Click on the trash can of a job punishment
```

**Comment by hugoheml** [comment]
Fixed in `kbrp-dashboard` `v1.0.12` version

**Comment by talarmin29** [comment]
Bug still present.

![Capture11](https://github.com/KB-RolePlay/tools-issues/assets/21173205/b8adda5f-62ce-4067-81af-06cac2dcf12b)
![Capture12](https://github.com/KB-RolePlay/tools-issues/assets/21173205/488cc740-7171-4724-8cef-fa417cc0559c)
